### ISSUE TITLE
Compilation Error

### ISSUE THREAD

**Issue by lilsaint41** [fguiet/AutomationServer#1]
Hello,
i would like to test your program but i'm facing compilation error.
`[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.6.0:compile (default-compile) on project automationserver-model: Compilation failure -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.6.0:compile (default-compile) on project automationserver-model: Compilation failure`

I run mvn clean package command on the parent project.
May you help me ?

**Comment by fguiet** [comment]
Hi @lilsaint41,

First, you have to build and run the application container, see https://github.com/fguiet/AutomationServer/tree/master/third-party-tools/automationserver/docker

Then from within the container, you can compile it by launching the following command : /applications/automationserver/cmd/deploy.sh

By the way, it is not impossible to test my program...but you have to build and run all the other docker containers first : see https://github.com/fguiet/AutomationServer/tree/master/third-party-tools

This project is very linked to my house...it can be use as a template for another house project but with some modifications
